// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_sw.Migrations
{
    [DbContext(typeof(MeuContexto))]
    [Migration("20250517135519_AtualizacaoTabelas")]
    partial class AtualizacaoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("api_sw.Models.TbLogin", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("TbLogin");
                });

            modelBuilder.Entity("api_sw.Models.TbStatus", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStatus");

                    b.ToTable("TbStatus");
                });

            modelBuilder.Entity("api_sw.Models.TbTarefas", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdStatusNavigationIdStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTarefa");

                    b.HasIndex("IdStatusNavigationIdStatus");

                    b.ToTable("TbTarefas");
                });

            modelBuilder.Entity("api_sw.Models.TbTarefas", b =>
                {
                    b.HasOne("api_sw.Models.TbStatus", "IdStatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdStatusNavigationIdStatus");

                    b.Navigation("IdStatusNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
